[mypy]
ignore_missing_imports = True
allow_untyped_calls = True
allow_untyped_defs = True
warn_unused_ignores = False

[mypy-vision_unlearning.unlearner.lora]
ignore_errors = True

[mypy-vision_unlearning.unlearner.uce_sd_erase]
ignore_errors = True
