"""Regenerate ``entity_names_expected.json`` from the task metadata on disk.

The fixture is the compatibility oracle for the entity-name transforms: it records, for every
entity of every task, the exact prompt the published corpus was generated with. The transforms
may be moved, rewritten or simplified; if any of these 300 strings changes, every image,
embedding and interference value already produced stops matching the code that produced it.

The metadata it reads lives under ``vision_unlearning/benchmarks/I_care/assets/``, which is
git-ignored, so continuous integration cannot read it -- which is exactly why the expected
values are committed here instead of being derived at test time. ``test_entity_names.py``
checks the fixture against the live metadata whenever that metadata is present, so the two
cannot drift apart unnoticed on a machine that has both.

Run from the repository root:

    PYTHONPATH=. .venv-lite/Scripts/python tests/fixtures/generate_entity_names_expected.py
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict, List

from vision_unlearning.datasets.testbed import get_target_overwrite

TASKS = ['people', 'breeds', 'scenes']
METHODS = ['distil', 'munba', 'uce', 'salun']
ASSETS = os.path.join('vision_unlearning', 'benchmarks', 'I_care', 'assets')
OUT = os.path.join('tests', 'fixtures', 'entity_names_expected.json')


def entity_names(task: str) -> List[str]:
    path = os.path.join(ASSETS, f'metadata_{task}_2_enriched_filtered.json')
    with open(path, 'r', encoding='utf-8') as handle:
        metadata = json.load(handle)
    return [entry['name'] for entry in metadata]


def main() -> int:
    payload: Dict[str, Any] = {
        '_README': (
            'Generated by tests/fixtures/generate_entity_names_expected.py. One row per entity: '
            'the metadata name, and the prompt the corpus was generated with. A change to any '
            '"generation_prompt" below orphans the published images, embeddings and interference '
            'values for that entity.'
        ),
        'tasks': {},
    }
    for task in TASKS:
        rows = []
        for name in entity_names(task):
            forms = {method: get_target_overwrite(task, method, name)[0] for method in METHODS}
            distinct = set(forms.values())
            if len(distinct) != 1:
                raise AssertionError(f'{task}/{name}: generation form depends on the method: {forms}')
            substitutes = {get_target_overwrite(task, method, name)[1] for method in METHODS}
            if len(substitutes) != 1:
                raise AssertionError(f'{task}/{name}: substitute concept depends on the method: {substitutes}')
            rows.append({
                'name': name,
                'generation_prompt': f'An image of {distinct.pop()}',
                'substitute_concept': substitutes.pop(),
            })
        payload['tasks'][task] = rows
        print(f'{task}: {len(rows)} entities')

    with open(OUT, 'w', encoding='utf-8') as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write('\n')
    print(f'wrote {OUT}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
